library(caret)

dataset2=read.csv('diabetes-f2.csv')

dataset2[,1:5]=scale(dataset2[,1:5])

control <- trainControl(method="repeatedcv", number=10, repeats=10)
metric <- "Accuracy"


rf<- function(x){
  set.seed(7)
  return(train(as.character(Outcome)~., data=dataset2, metric=metric, method=x, trControl=control)) 
} 

#fit.adaboost=rf("adaboost")
fit.treebag2=rf("treebag")
fit.vglmAdjCat2=rf("vglmAdjCat")
fit.bayesglm2=rf("bayesglm")
fit.rpart1SE2=rf("rpart1SE")
fit.rpart22=rf("rpart2")
fit.ctree22=rf("ctree2")
fit.vglmContRatio2=rf("vglmContRatio")
fit.rpartcost2=rf("rpartCost")
fit.vglmCumulative2=rf("vglmCumulative")
fit.gamLoess2=rf("gamLoess")
fit.RFlda2=rf("RFlda")
fit.glmStepAIC2=rf("glmStepAIC")
fit.glmnet2=rf("glmnet")
fit.protoclass2=rf("protoclass")
fit.kknn2=rf("kknn")
fit.svmLinearWeights2=rf("svmLinearWeights2")
fit.svmLinear32=rf("svmLinear3")
fit.lda2=rf("lda2")
fit.loclda2=rf("loclda")
fit.mlpML2=rf("mlpML")
fit.gcvEarth2=rf("gcvEarth")
fit.naive_bayes2=rf("naive_bayes")
fit.null2=rf("null")
fit.parRF2=rf("parRF")
fit.widekernelpls2=rf("widekernelpls")
fit.pda2=rf("pda")
fit.pda22=rf("pda2")
fit.plr2=rf("plr")
fit.multinom2=rf("multinom")
fit.rda2=rf("rda")
fit.regLogistic2=rf("regLogistic")
fit.linda2=rf("Linda")
fit.RSimca2=rf("RSimca")
fit.rocc2=rf("rocc")
fit.part2=rf("PART")
fit.sda2=rf("sda")
fit.c5rules2=rf("C5.0Rules")
fit.c5trees2=rf("C5.0Tree")
fit.oneR2=rf("OneR")
fit.sdwd2=rf("sdwd")
fit.sparseLDA2=rf("sparseLDA")
fit.slda2=rf("slda")
fit.gbm2=rf("gbm")

fit.glmboost2=rf("glmboost")
fit.gamboost2=rf("gamboost")
fit.logitboost2=rf("LogitBoost")
fit.rpart2=rf("rpart")
fit.ctree2=rf("ctree")
fit.bstLm2=rf("BstLm")
fit.knn2=rf("knn")
fit.nb2=rf("nb")
#fit.j48=rf("J48")
fit.c52=rf("C5.0")
fit.lda2=rf("lda")
#fit.ada=rf("ada")
fit.svmLinear2=rf("svmLinear")
fit.svmRadial2=rf("svmRadial")
fit.hdda2=rf("hdda")
fit.qda2=rf("qda")
fit.LMT2=rf("LMT")
fit.nnet2=rf("nnet")
fit.pda2=rf("pda")
fit.mda2=rf("mda")
fit.lvq2=rf("lvq")
fit.Mlda2=rf("Mlda")
fit.fda2=rf("fda")
fit.pam2=rf("pam")
fit.kernelpls2=rf("kernelpls")
fit.pls2=rf("pls")
fit.gpls2=rf("gpls")
#fit.rf=rf("rf")
fit.mlp2=rf("mlp")
fit.glm2=rf("glm")


results2=resamples(list(treebag=fit.treebag2,glmboost=fit.glmboost2,gamboost=fit.gamboost2,rpart=fit.rpart2,
                       ctree=fit.ctree2,knn=fit.knn2,nb=fit.nb2,LDA=fit.lda2,C5=fit.c52,SVMLinear=fit.svmLinear2, 
                       SVMRadial=fit.svmRadial2, LMT=fit.LMT2, PDA=fit.pda2,       
                       HDDA=fit.hdda2,QDA=fit.qda2, MDA=fit.mda2, LVQ=fit.lvq2,
                       LogitBoost=fit.logitboost2, MLDA=fit.Mlda2,FDA=fit.fda2,PAM=fit.pam2,
                       KERNELPLS=fit.kernelpls2,GPLS=fit.gpls2,MLP=fit.mlp2,GLM=fit.glm2))

bwplot(results2)
